version: 1

steps:
  - step:
      phase: install
      image: node
      cache: 
        - package.json
        - package-lock.lock
      commands:
        - npm install

  - step:
      phase: test
      name: lint
      commands:
        - npm run lint

  - step:
      phase: test
      name: e2e tests
      commands:
        - npm run test

